export const user =[
    {
        id: 1,
        name: {
            firstname: "Ria Mae",
            lastname: "Angcahan",
        },
        course: "BS Information Technology",
        year: 3,
        section: "A",
        userType: "Student",
        username: "iamRiyami",
        password: "@riaAngcahan",
    },
    {
        id: 2,
        name: {
            firstname: "Sheilo",
            lastname: "Saraga",
        },
        course: "BS Information Technology",
        year: 3,
        section: "A",
        userType: "Student",
        username: "shiloyy",
        password: "_loshei123",
    },
    {
        id: 3,
        name: {
            firstname: "Jesrel",
            lastname: "Pilipino",
        },
        course: "BS Information Technology",
        year: 3,
        section: "A",
        userType: "Student",
        username: "jesrel",
        password: "philippines",
    },
    {
        id: 4,
        name: {
            firstname: "Jerry",
            lastname: "Ale",
        },
        course: "",
        year: '',
        section: "",
        userType: "Teacher",
        username: "jerryAle",
        password: "@Alejerry_012",
    },
    {
        id: 5,
        name: {
            firstname: "Kathrine Mae",
            lastname: "Ayuban",
        },
        course: "BS Information Technology",
        year: 3,
        section: "A",
        userType: "Student",
        username: "katerinnn",
        password: "ayuban06_keem",
    },
    {
        id: 6,
        name: {
            firstname: "Catherine Leah",
            lastname: "Gabo",
        },
        course: "",
        year: '',
        section: "",
        userType: "Teacher",
        username: "@cathleah",
        password: "gabo_cathyy",
    },
    {
        id: 7,
        name: {
            firstname: "Winzeal",
            lastname: "Agoc",
        },
        course: "",
        year: '',
        section: "",
        userType: "Teacher",
        username: "_zyl",
        password: "winzeal123",
    },
    {
        id: 8,
        name: {
            firstname: "Karl Patrick",
            lastname: "Loquias",
        },
        course: "BS Information Technology",
        year: 3,
        section: "B",
        userType: "Student",
        username: "yiZhanIsReal",
        password: "karLami",
    },
    {
        id: 9,
        name: {
            firstname: "Jillian Cassandra",
            lastname: "Balon",
        },
        course: "BS Computer Science",
        year: 3,
        section: "",
        userType: "Student",
        username: "saeko",
        password: "jillzzz09",
    },
    {
        id: 10,
        name: {
            firstname: "Rhizabelle Jhaine",
            lastname: "Dalen",
        },
        course: "BS Information Technology",
        year: 3,
        section: "A",
        userType: "Student",
        username: "xabelsxx",
        password: "gwapaKo123",
    },
];